_base_ = [
    # '../_base_/models/maskclip_vit16.py',
    '../_base_/datasets/pascal_voc12_aug_20.py',
    # '../_base_/models/maskclip_vit16.py', '../_base_/datasets/pascal_voc12_aug.py',
    '../_base_/default_runtime.py',
    '../_base_/schedules/schedule_20k.py',
]

in_channels = 512
out_indices = [11]
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoderFSS',
    backbone=dict(
        type='VisionTransformer',
        img_size=(224, 224),
        patch_size=16,
        patch_bias=False,
        in_channels=3,
        embed_dims=768,
        num_layers=12,
        num_heads=12,
        mlp_ratio=4,
        out_indices=out_indices,
        qkv_bias=True,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        with_cls_token=True,
        output_cls_token=False,
        norm_cfg=dict(type='LN', eps=1e-6),
        act_cfg=dict(type='GELU'),
        patch_norm=False,
        pre_norm=True,
        final_norm=True,
        return_qkv=True,
        interpolate_mode='bicubic',
        num_fcs=2,
        norm_eval=False,
    ),
    decode_head=dict(
        type='ATMSingleHead',
        img_size=224,
        in_channels=512,
        channels=512,
        num_classes=1,
        num_layers=3,
        num_heads=8,
        use_stages=len(out_indices),
        embed_dims=in_channels,
        # embed_dims=in_channels // 2,
        loss_decode=dict(
            type='ATMLoss',
            num_classes=1,
            dec_layers=len(out_indices),
            loss_weight=1.0,
        ),
    ),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'),
)
